### ISSUE TITLE
Usage documentation?

### ISSUE THREAD

**Issue by joeyballentine** [WyattBlue/pyav#18]
Hi. I was interested in testing out this fork/package due to it both having type hints (which is incredible) and just being generally improved from the root repo.

However, it seems the API is a bit different from the main package. Is there any documentation available on what these changes are?

One example seems to be that you can't do `.add_stream` to an output container. I see that `.add_stream` exists on the container's `streams` field, but that takes in a Stream, and I can't seem to figure out how to initialize one.

Another difference seems to be that `.decode()` doesn't exist on packets.

A guide for how to transition from `av` to `pyav` would be greatly appreciated

**Comment by WyattBlue** [comment]
You can view the docs at https://pyav.basswood-io.com/
`pyav` and `av` have been merged, so there should be a difference in the API between av 12.0.0 and pyav 12.x
