### ISSUE TITLE
Wheels contain an out-of-date version of FFmpeg

### ISSUE THREAD

**Issue by benrg** [WyattBlue/pyav#4]
The wheels on PyPI seem to be based on FFmpeg 5.1.2, though 5.1.3 and 6.0 have been out for a while.

**Comment by WyattBlue** [comment]
I built ffmpeg 6.0 for Linux and MacOS using https://github.com/wyattblue/pyav-ffmpeg in the 11.3.0 release. Building ffmpeg  for Windows blew up Github Actions, it always failed because the container ran out of memory. I'm trying to build it using my Windows laptop, so we'll see how that goes.
