### ISSUE TITLE
Expose side_data of a stream

### ISSUE THREAD

**Issue by WouldYouKindly** [WyattBlue/pyav#5]
Hi, thanks a ton for the fork! 

I'm not sure what your intention is w.r.t. open issues in the original repo, but the one I'm particularly interested in is https://github.com/PyAV-Org/PyAV/issues/1045 - rotation metadata are not available on video streams. 

It looks like there's already a PR to fix this (https://github.com/hyenal/PyAV/pull/1).

**Comment by WyattBlue** [comment]
Sure. I've merged that PR and it will be available in the `11.2.0` release.
